// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS1ufeVRW9UdESx4W7YFUiX2oiE0fZDNw',
    appId: '1:69878415332:web:2e04ecaaeaec007c9d11f1',
    messagingSenderId: '69878415332',
    projectId: 'ecommerce-1a433',
    authDomain: 'ecommerce-1a433.firebaseapp.com',
    storageBucket: 'ecommerce-1a433.appspot.com',
    measurementId: 'G-ZBD4521G15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABkLBd0smyd5OxO6OWVCgsvRrDokRqR4',
    appId: '1:69878415332:android:6ca650b80f24c0c99d11f1',
    messagingSenderId: '69878415332',
    projectId: 'ecommerce-1a433',
    storageBucket: 'ecommerce-1a433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIj5C7Zfj3MhXssafoLOE8UjclICDRCxc',
    appId: '1:69878415332:ios:5e8704f9d0014ab49d11f1',
    messagingSenderId: '69878415332',
    projectId: 'ecommerce-1a433',
    storageBucket: 'ecommerce-1a433.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIj5C7Zfj3MhXssafoLOE8UjclICDRCxc',
    appId: '1:69878415332:ios:5e8704f9d0014ab49d11f1',
    messagingSenderId: '69878415332',
    projectId: 'ecommerce-1a433',
    storageBucket: 'ecommerce-1a433.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS1ufeVRW9UdESx4W7YFUiX2oiE0fZDNw',
    appId: '1:69878415332:web:36e95d17d3b664af9d11f1',
    messagingSenderId: '69878415332',
    projectId: 'ecommerce-1a433',
    authDomain: 'ecommerce-1a433.firebaseapp.com',
    storageBucket: 'ecommerce-1a433.appspot.com',
    measurementId: 'G-MM80DNNZN5',
  );
}
